[project]
name = "poolmind"
description = "PoolMind is a Stack-based arbitrage trading bot"
authors = ["@poolmind"]
telemetry = true
cache_dir = "./.cache"

[contracts.poolmind]
path = "contracts/poolmind.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
